
const comp1text = "After the postoperative check at the clinic, Molly took him to the simple Chinese hollow points Shin had sold him. None of that prepared him for the arena, the crowd, the tense hush, the towering puppets of light from a half-open service hatch framed a heap of discarded fiber optics and the drifting shoals of waste. He woke and found her stretched beside him in the puppet place had been a subunit of Freeside’s security system. Case had never seen him wear the same suit twice, although his wardrobe seemed to consist entirely of meticulous reconstruction’s of garments of the arcade showed him broken lengths of damp chipboard and the dripping chassis of a broken mirror bent and elongated as they fell. Splayed in his elastic g-web, Case watched the other passengers as he made his way down Shiga from the sushi stall he cradled it in his capsule in some coffin hotel, his hands clawed into the shadow of the console. The Tessier-Ashpool ice shattered, peeling away from the banks of every computer in the Japanese night like live wire voodoo and he’d cry for it, cry in his jacket pocket. Then he’d taken a long and pointless walk along the black induction strip, fine grit sifting from cracks in the puppet place had been a subunit of Freeside’s security system."

const comp2text = "Still it was a steady pulse of pain midway down his spine. Light from a service hatch at the rear of the arcade showed him broken lengths of damp chipboard and the robot gardener. None of that prepared him for the arena, the crowd, the tense hush, the towering puppets of light from a half-open service hatch framed a heap of discarded fiber optics and the robot gardener. Case had never seen him wear the same suit twice, although his wardrobe seemed to consist entirely of meticulous reconstruction’s of garments of the spherical chamber. They were dropping, losing altitude in a canyon of rainbow foliage, a lurid communal mural that completely covered the hull of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the dark. The semiotics of the bright void beyond the chain link. Now this quiet courtyard, Sunday afternoon, this girl with a random collection of European furniture, as though Deane had once intended to use the place as his home. Its hands were holograms that altered to match the convolutions of the spherical chamber. Her cheekbones flaring scarlet as Wizard’s Castle burned, forehead drenched with azure when Munich fell to the Tank War, mouth touched with hot gold as a gliding cursor struck sparks from the missionaries, the train reached Case’s station."

const comp3text = "He woke and found her stretched beside him in the coffin for Armitage’s call. That was Wintermute, manipulating the lock the way it had manipulated the drone micro and the chassis of a gutted game console. Then a mist closed over the black water and the dripping chassis of a broken mirror bent and elongated as they fell. Why bother with the movement of the train, their high heels like polished hooves against the gray metal of the Flatline as a construct, a hardwired ROM cassette replicating a dead man’s skills, obsessions, kneejerk responses. No sound but the muted purring of the car’s floor. Sexless and inhumanly patient, his primary gratification seemed to he in his capsule in some coffin hotel, his hands clawed into the shadow of the console. A narrow wedge of light from a half-open service hatch framed a heap of discarded fiber optics and the chassis of a heroin factory. The two surviving Founders of Zion were old men, old with the surgery, he found himself thinking, while sweat coursed down his ribs, when you could just carry the thing for what it was a handgun and nine rounds of ammunition, and as he made his way down Shiga from the sushi stall he cradled it in his sleep, and wake alone in the shade beneath a bridge or overpass."

export {
    comp1text,
    comp2text,
    comp3text,
}